### PR TITLE
chore: add catalog-info and enable blank PR

### PR DESCRIPTION
**Pull request by ichintanjoshi**
## Description

- added catalog-info.yaml 
- changed github issue template file

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ichintanjoshi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by ichintanjoshi** [comment]
@sarina let me know if this is up to the mark

**Review by sarina — APPROVED** [review]

**Comment by sarina** [comment]
Hi @ichintanjoshi - when I said "squash to two commits", I was looking for a commit history of two logical commits where each commit does exactly one thing. It would look like this:

```
chore: enable blank pull requests
chore: add catalog-info
```

But seeing as you're learning rebasing and squashing now, I'll just merge this. I recommend you go to your original branch and see if you can figure out how to get your original commit history down to these two.

**Comment by openedx-webhooks** [comment]
@ichintanjoshi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/registrar&entry.867055334=https://github.com/openedx/registrar/pull/626&entry.1484655318=https://github.com/ichintanjoshi&entry.752974735=2024-06-20+12:59&entry.1917517419=2024-06-20+20:30&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
