### PR TITLE
Ignore read-only/old jobs when checking conflicts

### PR DESCRIPTION
**Pull request by kdmccormick**
@edx/masters-neem 

**Motivation**
Curtin will be not be able to run new enrollment-writing jobs due to two enrollment-reading jobs that are currently stuck in the Pending state.

**Description**
Currently, we disallow any enrollment-writing job from starting if the associated program has any
jobs in the one of processing states (IN PROGRESS, RETRYING, and PENDING). This commit relaxes that constraint in two ways:
* Only block if a 'write' job is processing
* Ignore jobs of a certain age (currently 30 minutes)

The reason for the second relaxation is that jobs ocassionally becomes 'stuck' in the PENDING state, so
we have to modify the database to unblock future jobs for that program. This is not desirable, so we can assume that any job older than 30 minutes will never complete.

If Registrar begins to have longer-running jobs, then the maximum age may need to be reconsidered.

### CODE REVIEW

**Comment by zacharis278** [comment]
wondering if it would make more sense to just set a timeout on our celery tasks instead of ignoring jobs that never complete?

**Comment by kdmccormick** [comment]
@zacharis278 that does seem like a nicer solution, assuming the timeout could mark task as Failed.

**Comment by zacharis278** [comment]
Yeah unfortunately my solution is unlikely to fix the current state.  If we're unsure about the cause and if the timeout response will get persisted.  I'd recommend putting in both solutions so we can track the behavior without blocking partners while we fix the DB.  If the timeout does work, we can can clean it up to rely on that going forward.  Rather not have a bunch of mystery pending jobs around that may or may not be holding up workers.

**Comment by kdmccormick** [comment]
@Zacharis278 Fortunately, the only stuck jobs currently are Read jobs:
```
mysql> select name, state from user_tasks_usertaskstatus where state in ('Pending', 'Retrying', 'In Progress');
+-------------------------------------------------------------------------------+---------+
| name                                                                          | state   |
+-------------------------------------------------------------------------------+---------+
| online-master-in-marketing-curtin-university:read:list_program_enrollments    | Pending |
| online-master-in-marketing-curtin-university:read:list_course_run_enrollments | Pending |
+-------------------------------------------------------------------------------+---------+
2 rows in set (0.00 sec)
```
So, I could implement just the first part of this (ignore read-only jobs) to fix the existing issue, and then use Celery timeouts to prevent more jobs from getting stuck.

**Review by zacharis278 — APPROVED** [review]
@kdmccormick sounds good.  Don't think there is a good reason to block on readonly anyway.

**Comment by kdmccormick** [comment]
Closed in favor of https://github.com/edx/registrar/pull/170 + https://github.com/edx/registrar/pull/171

**Pull request closed without merging**
