### PR TITLE
Set celery exchange, rename default queue

### PR DESCRIPTION
**Pull request by jdmulloy**
We need to also set the celery exchange setting. I also made the default queue name 'registrar.default' in case we ever want more queues. It's fine to leave it as just registrar if we think the chance of other queues is low. I'd like the have all queues include the app name in them, so if a new queue is ever needed it should be registrar,foobar instead of just foobar so we know which IDA it goes with.

### CODE REVIEW

**Review by kdmccormick — COMMENTED** [review]
Sounds good, but I think we need to update https://github.com/edx/configuration/blob/master/playbooks/roles/registrar/defaults/main.yml#L142 too.

The right solution, of course, would be to set Registrar's `CELERY_DEFAULT_QUEUE` value based off the linked queue name setting...

Also, TBH, I don't know the difference between queue, routing key, and exchange, but I'll trust your knowledge that these values are sensible.

**Comment by iloveagent57** [comment]
https://docs.celeryproject.org/en/latest/userguide/routing.html#exchanges-queues-and-routing-keys

Yeah, we'll have to update the configuration code, too.  That code does stuff like telling the workers which queue they should listen to when supervisor spins them up.

**Review by iloveagent57 — APPROVED** [review]
Tagged you guys on this corresponding PR: https://github.com/edx/configuration/pull/5172

**Comment by kdmccormick** [comment]
@jdmulloy @iloveagent57 

how about:
```python
CELERY_DEFAULT_EXCHANGE = os.environ.get('CELERY_DEFAULT_EXCHANGE', 'registrar')
CELERY_DEFAULT_ROUTING_KEY = os.environ.get('CELERY_DEFAULT_ROUTING_KEY', 'registrar')
CELERY_DEFAULT_QUEUE = os.environ.get('CELERY_DEFAULT_QUEUE', 'registrar.default')
```

and then in https://github.com/edx/configuration/pull/5172:
```yaml
registrar_celery_default_queue: registrar.default
registrar_environment:
  ....
  CELERY_DEFAULT_EXCHANGE: registrar
  CELERY_DEFAULT_ROUTING_KEY: registrar
  CELERY_DEFAULT_QUEUE: "{{ registrar_celery_default_queue }}"
...
...
REGISTRAR_CELERY_WORKERS:
  - queue: "{{ registrar_celery_default_queue }}"
    ...

**Comment by iloveagent57** [comment]
@kdmccormick I like your suggestion, commit added to implement it.

**Review by kdmccormick — APPROVED** [review]
Awesome :ship:

**Pull request merged**
